# Default rich text styling configuration for Apple Mail MCP
# All colors are in web format (#RRGGBB)

# Color definitions using YAML anchors (x- prefix makes them ignorable extensions)
x-colors:
  dark_gray: &50_percent_gray "#7F7F7F"

defaults:
  font: "Helvetica"
  size: 12
  color: null

styles:
  # Headings
  h1:
    font: "Helvetica-Bold"
    size: 20
    color: null
    margin_top: 10
    margin_bottom: 5

  h2:
    font: "Helvetica-Bold"
    size: 18
    color: null
    margin_top: 8
    margin_bottom: 4

  h3:
    font: "Helvetica-Bold"
    size: 16
    color: null
    margin_top: 6
    margin_bottom: 2

  h4:
    font: "Helvetica-Bold"
    size: 14
    color: null
    margin_top: 4
    margin_bottom: 2

  h5:
    font: "Helvetica-Bold"
    size: 14
    color: null
    margin_top: 4
    margin_bottom: 2

  h6:
    font: "Helvetica-Bold"
    size: 14
    color: null
    margin_top: 4
    margin_bottom: 2

  # Inline styles
  bold:
    font: "Helvetica-Bold"

  italic:
    font: "Helvetica-Oblique"

  strikethrough:
    font: "Helvetica"
    color: *50_percent_gray

  bold_italic:
    font: "Helvetica-BoldOblique"

  code:
    font: "Menlo-Regular"
    size: 11
    color: null

  # Block styles
  code_block:
    font: "Menlo-Regular"
    size: 11
    color: null
    margin_top: 6
    margin_bottom: null
    prefix:
      content: "  "
      font: null
      size: null
      color: null

  blockquote:
    font: "Helvetica-Oblique"
    size: 12
    color: null
    margin_top: 6
    margin_bottom: 6
    prefix:
      content: "  "
      font: null
      size: null
      color: null

  list:
    margin_top: 6
    margin_bottom: 6

  list_item:
    font: "Helvetica"
    size: 12
    color: null

  horizontal_rule:
    font: "Helvetica"
    size: 1
    color: *50_percent_gray

  link:
    color: null
